### ISSUE TITLE
uskit 多个rank不生效

### ISSUE THREAD

**Issue by duanyu2018** [baidu/unit-uskit#14]
在flow.conf 文件中，调用多个排序策略，后面的排序策略不生效

//按技能定义排序
rank {
    name : "skill_rank"
    order: "get_child_education"
    order: "get_health_lecture"
    order: "get_animal_sounds"
    order: "get_chat"
}
//按技能的分数排序
rank {
    name : "skill_sort"

    sort_by {
        expr : "get($item, 'data/score')"
        desc : 1
    }
}

flow {
    name : "recall_skill"
    recall: "get_health_lecture"
    recall: "get_child_education"
    recall: "get_animal_sounds"
    recall: "get_chat"
//先按找分数排序取前2个技能
    rank {
        rule : "skill_sort"
	top_k : 2
    }
//再按照技能顺序，取第一个
     rank {
        rule : "skill_rank"
	input : "$rank"
	top_k : 1
    }
     output {
            key : "skill"
            expr : "get($rank, '/')"
     }
    if {
        cond : "len($rank) == 1"
        output {
            key : "skill"
            expr : "get($rank, '0')"
        }
        output {
            key : "data"
            expr : "get($backend, get($rank, '0') + '/data')"
        } 	
        next : "set_session"
    }
    next : "default"
}

看日志上输出，结果是有排序的，但是在 if 条件哪里取值的时候，取的是第一次排序后的值

**Comment by LuckySherry** [comment]
已线下修复，正在测试验证中
