### ISSUE TITLE
backend节点能不能动态生成

### ISSUE THREAD

**Issue by duanyu2018** [baidu/unit-uskit#16]
大量的配置都是重复的，能不能在在flow中动态的生成backend,或者动态的把url传给backend

**Comment by LuckySherry** [comment]
v1.0.1版本的uskit仅支持所有backend后端服务在uskit启动前已经在conf文件中完整定义访问的url。如果大部分配置指的是service request/response配置的话可以使用request/response_template，具体可以看config.md

**Comment by ShaneTian** [comment]
> 大量的配置都是重复的，能不能在在flow中动态的生成backend,或者动态的把url传给backend

现版本支持动态 HTTP 请求，请在 [config.md](https://github.com/baidu/unit-uskit/blob/master/docs/config.md) 查看 `dynamic_args_node` 等相应的参数配置
