### ISSUE TITLE
支持对redis进行配置吗

### ISSUE THREAD

**Issue by gfcgfl** [baidu/unit-uskit#21]
假如我的redis配置了用户名密码，等，能够在uskit中对redis这些属性进行配置吗

**Comment by breaveSun** [comment]
请问解决了么 哪里可以设置密码

**Comment by ShaneTian** [comment]
可以通过 `redis_cmd ` 配置

https://github.com/baidu/unit-uskit/blob/ee283f3be42a1dadaef80751d4ed4358ee83c2e8/docs/config.md
