### ISSUE TITLE
启动USkit时报错

### ISSUE THREAD

**Issue by guet3401** [baidu/unit-uskit#3]
![image](https://user-images.githubusercontent.com/15119094/53459061-66b07080-3a73-11e9-9b68-0c66bf486de4.png)
 依赖环境安装都已经装了，配置文件在demo上修改的，启动时报这个错误。不知道哪里出问题了

**Comment by swpd** [comment]
确认端口8888是否被其他服务占用。

**Comment by guet3401** [comment]
非常感谢，确实是端口被占用了，指定端口后可以正常启动，调用回复都是默认的，我的技能中配置了天气、闲聊等技能。这是一次调用时完整的日志，是因为我的网络有限制吗？
![image](https://user-images.githubusercontent.com/15119094/53462645-86e62c80-3a7f-11e9-8ce4-7d81e34d35ff.png)

**Comment by coneycode** [comment]
端口占用这个问题，您得看自己的机器环境了。可能您别的服务使用了这个端口，具体您可以搜一下查看端口的相关指令。

**Comment by swpd** [comment]
这个看起来是获取UNIT Access Token的时候出错了，可以参考http://ai.baidu.com/docs#/Auth/top 里对应的错误码进行排查
![image](https://user-images.githubusercontent.com/3040031/53464634-e6dfd180-3a85-11e9-8923-f325bd5c6f8c.png)

**Comment by guet3401** [comment]
![image](https://user-images.githubusercontent.com/15119094/53466002-0f1dff00-3a8b-11e9-937e-3ecacbcb3b9d.png)
我的Access Key就是在“安全认证 / Access Key”中获得的，如果不通过这种方式，那应该怎么获得呢？
