### ISSUE TITLE
编译时找不到md5文件

### ISSUE THREAD

**Issue by breaveSun** [baidu/unit-uskit#30]
-- Configuring done
-- Generating done
-- Build files have been written to: /www/kit/unit-uskit/_build
[  2%] [FLEX][EXPR_LEXER] Building scanner with flex 2.5.37
[  5%] Running cpp protocol buffer compiler on proto/us.proto
[  8%] Running cpp protocol buffer compiler on proto/config.proto
[ 11%] [BISON][EXPR_PARSER] Building parser with bison 3.0.4
Scanning dependencies of target uskit
[ 14%] Building CXX object CMakeFiles/uskit.dir/src/backend.cpp.o
In file included from /www/kit/unit-uskit/src/common.h:19:0,
                 from /www/kit/unit-uskit/src/dynamic_config.h:22,
                 from /www/kit/unit-uskit/src/backend.h:22,
                 from /www/kit/unit-uskit/src/backend.cpp:15:
/www/kit/unit-uskit/src/butil.h:28:37: 致命错误：butil/md5.h：没有那个文件或目录
 #include BUTIL_INCLUDE_PREFIX/md5.h>
                                     ^
编译中断。
make[2]: *** [CMakeFiles/uskit.dir/src/backend.cpp.o] 错误 1
make[1]: *** [CMakeFiles/uskit.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by YuanWeihao1** [comment]
你好朋友，我也遇到这个问题，请问你的问题解决了吗，如何解决的

**Comment by HuangLK** [comment]
看起来是brpc版本的问题，试一下0.9.5的版本，这个版本还是有md5.h的。
https://github.com/apache/incubator-brpc/blob/0.9.5/src/butil/md5.h

**Comment by ShaneTian** [comment]
@breaveSun @YuanWeihao1 
新版的 brpc 删除了 `md5.h`，修改为包含 `md5.h` 的版本即可。

将 `deps.sh` 中有关 brpc 的部分修改为：
```sh
echo "Updating brpc..."
cd brpc
git checkout master
git pull
git checkout 2ae7f04ce513c6aee27545df49d5439a98ae3a3f
```
该 commit 是包含 `md5.h` 的
