### ISSUE TITLE
Failed to receive response from service [get_access_token] 

### ISSUE THREAD

**Issue by twoyoungtwosimple** [baidu/unit-uskit#31]
logid=794248 Failed to receive response from service [get_access_token] remote_server=127.0.0.1:6379 latency=43us error_msg=[E112]Not connected to 127.0.0.1:6379 yet, server_id=1 [R1][E112]Not connected to 127.0.0.1:6379 yet, server_id=1

这需要修改哪个配置文件啊？ 之前没问题，现在突然出现这个问题。

**Comment by ShaneTian** [comment]
> logid=794248 Failed to receive response from service [get_access_token]

说明 `backend.conf` 中 `get_access_token` service 请求失败，需要定位该 service 相关问题
