### ISSUE TITLE
backend配置 UNIT的技能对话接口的URL的问题

### ISSUE THREAD

**Issue by YuanWeihao1** [baidu/unit-uskit#33]
向uskit发送请求的时候报错：logid=123456 Failed to receive response from service [faq_1018537] remote_server=163.177.151.89:443 latency=31667us error_msg=[E1010]HTTP/1.1 500 Internal Server Error

backend.conf配置是
backend {
    name : "token_backend"
    server : "aip.baidubce.com"
    protocol : "http"
    connect_timeout_ms : 500
    timeout_ms : 1000
    max_retry : 1

    service {
        name : "fetch_access_token"
        request {
            http_method : "post"
            http_uri : "/oauth/2.0/token"

            http_header {
                key : "Content-Type"
                value : "application/json"
            }

            http_header {
                key : "Host"
                value : "aip.baidubce.com"
            }

            http_query {
                key : "grant_type"
                value : "client_credentials"
            }

            http_query {
                key : "client_id"
                # 替换为你的API Key
                value : "KcloAo9At6xxjwbFcCGu0L1i"
            }

            http_query {
                key : "client_secret"
                # 替换为你的Secret Key
                value : "hkkijWm4rpEiyDjeF2aimQy8lXFIOyCu"
            }
        }

**Comment by ShaneTian** [comment]
> logid=123456 Failed to receive response from service [faq_1018537]

说明是 `faq_1018537` service 请求失败，烦请定位该 service 相关问题
