### ISSUE TITLE
USkit的返回参数可以配置识别的槽值吗？

### ISSUE THREAD

**Issue by guet3401** [baidu/unit-uskit#4]
例如用户的query=“今天北京的天气怎么样”，返回的参数中包含time和locate。这样通过USkit调用后得到相应的槽值，用户可以去访问第三方资源

**Comment by swpd** [comment]
可以的，需要修改一下backend.conf和flow.conf，将原始返回结果中相应的字段输出到最终结果中。具体配置语法可以参考下 https://github.com/baidu/unit-uskit/blob/master/docs/config.md

**Comment by guet3401** [comment]
请问get(json, path[, default_value=null])函数，可以获取技能响应的json串里面的一个数组的值吗，我在backend.conf这样配置的
![image](https://user-images.githubusercontent.com/15119094/53552669-d196a000-3b76-11e9-8c29-858c3b8a2bbf.png)
在flow.conf中这样获取
![image](https://user-images.githubusercontent.com/15119094/53552852-4a95f780-3b77-11e9-9deb-72334435c504.png)
在API调用返回结果中为null，是不支持还是我的配置有问题，如果我想获取返回结果中的json中一个数组应该怎么办，配置中是否支持循环取某一个值？关于自定义函数的说明链接也没有了。

**Comment by swpd** [comment]
1. 支持获取数组，你可以先试着按路径由浅往深逐步调试，看看技能响应里是不是包含了相应的字段。
2. 自定义函数说明：https://github.com/baidu/unit-uskit/blob/master/docs/custom.md

**Comment by zpcwr** [comment]
> 可以的，需要修改一下backend.conf和flow.conf，将原始返回结果中相应的字段输出到最终结果中。具体配置语法可以参考下 https://github.com/baidu/unit-uskit/blob/master/docs/config.md

有没有简单的demo可以参考下呢？
