### ISSUE TITLE
backend怎么配置呢

### ISSUE THREAD

**Issue by leshphonc** [baidu/unit-uskit#40]
server 不能配置成 http://www.a.com/new 这种形式吗？因我我要通过/new去做负载。

如果不支持/new的话，load_balancer该如何配置呢，可以给个例子吗，谢谢。
brpc不太会用。。

**Comment by ShaneTian** [comment]
server 的 URL path 通过 conf/gflags.conf 中的 `--url_path` 参数进行配置
