### ISSUE TITLE
 mkdir _build && cd _build && cmake .. && make  出错

### ISSUE THREAD

**Issue by ssvip9527** [baidu/unit-uskit#5]
mkdir _build && cd _build && cmake .. && make

-- Build files have been written to: /Users/dreamxyp/Transcend/git/unit-uskit/_build
[  3%] [FLEX][EXPR_LEXER] Building scanner with flex 2.5.35
[  6%] Running cpp protocol buffer compiler on proto/us.proto
[ 10%] Running cpp protocol buffer compiler on proto/config.proto
[ 13%] [BISON][EXPR_PARSER] Building parser with bison 2.3
src/expression/parser.yy:18.10-16: require bison 3.0.4, but have 2.3
make[2]: *** [parser.cpp] Error 63
make[1]: *** [CMakeFiles/uskit.dir/all] Error 2
make: *** [all] Error 2

**Comment by swpd** [comment]
> src/expression/parser.yy:18.10-16: require bison 3.0.4, but have 2.3

bison版本太老了，升级到3.0.4或以上
